<?php
//DADOS
echo "DIRETÓRIO RAIZ: $_SERVER[DOCUMENT_ROOT] <br>";
echo "CAMINHO DO SCRIPT: $_SERVER[SCRIPT_NAME] <br>";
echo "CAMINHO ABSOLUTO DO SCRIPT: $_SERVER[SCRIPT_FILENAME] <br>";
echo "IDENTIFICAÇÃO DO SERVIDOR: $_SERVER[SERVER_SOFTWARE] <br>";
echo "NOME DO SERVIDOR: $_SERVER[SERVER_NAME] <br>";
echo "PORTA SERVIDOR: $_SERVER[SERVER_PORT] <br>";
?>
